### ISSUE TITLE
[Question] So how do I download this shader to play?

### ISSUE THREAD

**Issue by LOKSTED** [zombye/spectrum#1]
It looks amazing but minecrafthub just put me in this page when I try to download. Do I have to download and zip it myself??

**Comment by Rh0k41** [comment]
> It looks amazing but minecrafthub just put me in this page when I try to download. Do I have to download and zip it myself??

on the first <> Code page click the green code button and click "download zip"

**Comment by zombye** [comment]
As mentioned already, on the main code page, click the green `<> Code` button, and select "Download ZIP" from the dropdown menu.
From here, it can be installed the same way as any other shaderpack.
